services:
  nginx:
    build: infra/dev/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - django_network

  db:
   container_name: db
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   networks:
     - django_network
   env_file:
     - .env

  django:
   build: .
   container_name: django
   ports:
     - "8000:8000"
   networks:
     - django_network
   depends_on:
     - db
   env_file:
     - .env
   volumes:
    - ./:/app

networks:
  django_network:
    driver:
        bridge

volumes:
   postgres_data: